services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=main
    volumes:
      - ./db:/bitnami/mariadb
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - mariadb
  laravel:
    image: docker.io/bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_DATABASE=main
    ports:
      - '8000:8000'
    volumes:
      - ./workspace:/workspace
    container_name: laravel
    stdin_open: true
    tty: true
    depends_on:
      - mariadb
  

